### ISSUE TITLE
Boxy Boo will not spawn

### ISSUE THREAD

**Issue by MizTheWitch** [W-Baldwin/LethalPlaytime#2]
After no sign of boxy boo at all I decided to mess with spawn precents and see if I could get him to load. No matter what I do I cannot get boxy boo to spawn, I put his spawn rate at 100% and checked multiple moons (experimentation, march and titan) But no matter what I do not seem to get him to spawn, I now the sliders are working because I set huggy wuggy, dog day and miss delightful to 0 to try and force him to spawn but still 0 sign of him.

**Comment by W-Baldwin** [comment]
Hello there!  Could you verify that you were using the latest version 1.3.4?   This was an issue with the initial release of Boxy and should be fixed in the current version.

**Comment by MizTheWitch** [comment]
I am on version 1.3.4, I doubled checked to make sure. here's an image showing everything is up to date
![image](https://github.com/user-attachments/assets/333603ea-4136-42dd-bcf8-7de7d292d31f)

**Comment by W-Baldwin** [comment]
![image](https://github.com/user-attachments/assets/d8de1d6f-6462-4fac-aa7a-818bb214ed07)
So I have issues seeing him as well sometimes but I think its more about the rarity limits being too low at the current 100% value.  You can still get pretty unlucky and never see him is what I'm saying.  What I am going to do is make the maximum rarity you can set them to as 4x higher than what is possible right now, which would almost guarantee you see them at least once per visit.  It would still be possible to get unlucky but far less likely.

I will release [1.3.5] tonight with this change to rarity values!

**Comment by W-Baldwin** [comment]
Hey I've been able to get Boxy to spawn many times and I've had some other people test it and they can see him spawn too.  Just remember that even at 100% rarity its still possible to get severely unlucky and not see Boxy.  

The change I've made in order to help you or anyone that wanted to guarantee an experience with any particular creature in my mod is quadrupling the maximum rarity you can set for each creature.  This would almost guarantee you see them on every run on moons that had a decently high maximum power level.  Boxy has a power level of 2.5 and if the moon's already full of other creatures it won't be able to spawn him.
